# Generated by Django 5.1.3 on 2024-12-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('main', '0002_alter_products_category_alter_topping_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default='Неизвестный товар', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.products', verbose_name='Товар'),
        ),
    ]
