# Generated by Django 5.1.3 on 2024-12-18 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'catrgory',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='topping_images', verbose_name='Изображение')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Ккал')),
                ('protein', models.PositiveIntegerField(default=0, verbose_name='Белки')),
                ('fats', models.PositiveIntegerField(default=0, verbose_name='Жиры')),
                ('carb', models.PositiveIntegerField(default=0, verbose_name='Углеводы')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('types', models.CharField(max_length=150, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Топинг',
                'verbose_name_plural': 'Топинги',
                'db_table': 'topping',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Изображение')),
                ('structure', models.TextField(blank=True, null=True, verbose_name='Состав')),
                ('weight', models.PositiveIntegerField(default=250, verbose_name='Вес')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Ккал')),
                ('protein', models.PositiveIntegerField(default=0, verbose_name='Белки')),
                ('fats', models.PositiveIntegerField(default=0, verbose_name='Жиры')),
                ('carb', models.PositiveIntegerField(default=0, verbose_name='Углеводы')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
    ]
