# Generated by Django 5.1.3 on 2024-12-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default='Неизвестная категория', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='types',
            field=models.ForeignKey(default='Неизвестный тип добавки', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.typetopping', verbose_name='Тип добавки'),
        ),
    ]
