# Generated by Django 5.1.3 on 2024-12-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_products_carb_alter_products_fats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='carb',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='products',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='products',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='carb',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Белки'),
        ),
    ]
