# Generated by Django 5.1.3 on 2024-12-19 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_products_carb_alter_products_fats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Тип добавки')),
            ],
            options={
                'verbose_name': 'Тип добавки',
                'verbose_name_plural': 'Типы добавок',
                'db_table': 'typetop',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='topping',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typetopping', verbose_name='Тип добавки'),
        ),
    ]
