# Generated by Django 5.1.3 on 2024-12-24 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('is_student', models.BooleanField(verbose_name='Учишься')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('residence', models.CharField(max_length=255, verbose_name='Место проживания')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('marital_status', models.CharField(choices=[('single', 'Не женат/Не замужем'), ('married', 'Женат/Замужем'), ('divorced', 'Разведен(а)')], max_length=10, verbose_name='Семейное положение')),
                ('has_children', models.BooleanField(verbose_name='Есть дети')),
                ('work_experience', models.TextField(verbose_name='Опыт работы')),
                ('about_yourself', models.TextField(verbose_name='Расскажите о себе')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено')], default='pending', max_length=10, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
