# Generated by Django 5.1.3 on 2024-12-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ('id',), 'verbose_name': 'Заявку на работу', 'verbose_name_plural': 'Заявки на работу'},
        ),
    ]
